all :	hw4

hw4:	hw4.c
	gcc -o hw4 hw4.c -pthread -Wall

clean: 
	rm hw4

run:   
	./hw4 /home/berkay/Desktop/testPath/HW4,/homeworksToBeDone /home/berkay/Desktop/testPath/HW4,/studentsForHire 10000
