all :	hw1

hw1:	hw1.c
	gcc -o hw1 hw1.c -pthread -Wall

clean: 
	rm hw1

run:   
	./hw1 -w /home/berkay/Desktop/testPath -f an+e.txt -p rw-r--r--
#run2:	
#	./hw1 -w /home/berkay/Desktop/testPath -p rw-r--r--
#run3:
#	./hw1 -w /home/berkay/Desktop/testPath -f an+e.txt
#run4:	
#	./hw1 -w /home/berkay/Desktop/testPath -b 1111
#run5:	
#	./hw1 -w /home/berkay/Desktop/testPath -l 3
#run6:	
#	./hw1 -w / -l 1
#run7:
#	./hw1 -w /home/berkay/Desktop/testPath -f yedek.c
